딥러닝에서 로지스틱 회귀를 제일 많이 쓰기때문에
머신러닝에서는 기본적인것만 보고 넘어갈거

<모델>
1. fit
- 함수f(x)를 만들어내는 역할이 fit
- 그니까 fit은 수식만 기억하고 수행함
- 그 식을 적용하는건 transform이 함
- 모델을 만들어내는 데이터가 train데이터
- 우리가 지금하는건 지도학습(문제input와 답target이 다 있음)
- 지도학습은 두개의 파라미터값을 가짐(문제input와 답target)
- 문제:input(훈련용 train_input, train_target)
2. predict
- f(x)에 새로운 예측값을 집어넣음
- 이 작업이 predict임 (예측값보여주는거)
- 이렇게 결과가 만들어짐
3. 평가지표(score...)
- 이 모델의 성능을 알아보는게 score(평가지표)함수
- 분류(정확도)
- 예측(회귀)
- ㄴR2에서는 결정계수라고 부름)

<전처리>
4. transform
- fit함수를 쓰고 transform함수를 씀
- target(정답/Species/종속변수)이 있고 이 타겟을 골라낼 특성데이터(문제/나머지컬럼들/독립변수)가 있는데
- 0에서1사이로 단위를 맞추는거(왜냐면 그게 확률값이므로)
- train_input데이터 하나만 작업하면 됨
- target은 안넣음
- 파라미터가 하나
-
- fit으로
- 표준화를 시켜야할 컬럼들이 뭐있는지 찾고
- 표준화를 시킴 (끝)
- 
- 실제 데이터에 반영은 transform이 함

### 정은이 필기
###학습을 시키는 알고리즘
fit. tredict, score 이 세가지를 쓴다.

함수 f(x)를 만드는 작업을 먼저한다 그게 분류가 됐든, 예측이 됐든
이 함수를 만들어내는 역할 이 'fit' <- 이것을 모델이라고 한다.


모델을 만들 때 사용하는 데이터 training data
지도 학습은 (문제와 정답을 가지고 있어야 한다.)
지도학습에서의 fit은 두개의 파라미터 값을 가지고 있다.(문제input(훈련이니깐 tarain의 input, 정답(target)

score(정확도, 평가 지표)
분류와 예측에서는 달리 표현
 예측이라는 것은 회귀에서는 R2결정계수
 분류에서는 정확도라고 표현  - score을 뽑아내는(계산하는)방식이 다르다.
 
 ###전처리는 fit, transform이라는 함수를 쓴다.
 (1) 표준화0에서 1로 맞춤(z value를 통해 정규화 시킴)
 우리가 골라낼 target이 있고 특성이 있는 input이 있다.(input만 건들고 얘들만 맞춰)
 fit이라는 함수에 input을 넣는다. fit의 파라미터는 하나다.
 표준화를 시켜야할 컬럼(특성)들이 무엇인지 찾는다
 그러고 표준화를 시켜
 실제 데이터의 반영은 transform이 한다.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## 데이터 로딩

In [2]:
fish = pd.read_csv('C:/k_digital/source/data/fish.csv')
fish.head()

Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961
3   Bream   363.0    29.0      33.5  12.7300  4.4555
4   Bream   430.0    29.0      34.0  12.4440  5.1340

In [3]:
# 데이터를 보면 처음 드는 생각은
# 단위가 다르니까 피쳐 스케일링을 해야겠다

In [4]:
# 어떤 물고기 종류가 있는지 살펴보기
fish['Species'].unique()
# 파이썬이 제공하는 함수
# 중복을 제거하고 고유값만 보여줌

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [5]:
pd.unique(fish['Species'])
# 판다스도 제공함

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [ ]:
# Species가 target 데이터가 되고 나머지가 input 데이터가 될꺼임
# 데이터를 쪼개야 됨

In [ ]:
# 머신으로 돌리려면 넘파이배열로 바꿔야함(데이터프레임)

In [8]:
fish_input = fish[['Weight','Length','Diagonal','Height','Width']].to_numpy()
# input데이터 뜯어내고
# 넘파이로 바꾸기

In [9]:
# 잘뜯어왔는지 보기
fish_input[:5]

array([[242.    ,  25.4   ,  30.    ,  11.52  ,   4.02  ],
       [290.    ,  26.3   ,  31.2   ,  12.48  ,   4.3056],
       [340.    ,  26.5   ,  31.1   ,  12.3778,   4.6961],
       [363.    ,  29.    ,  33.5   ,  12.73  ,   4.4555],
       [430.    ,  29.    ,  34.    ,  12.444 ,   5.134 ]])

In [10]:
fish_target = fish['Species'].to_numpy()
# target 데이터도 뜯어내고 넘파이로 바꾸기

In [13]:
# 확인
fish_target[:5]

array(['Bream', 'Bream', 'Bream', 'Bream', 'Bream'], dtype=object)

## 훈련세트와 테스트세트로 분리

In [14]:
from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target = train_test_split(
    fish_input, fish_target, random_state=42)

# random_state=42 : seed 값 고정하는거랑 동일
# 여러번 수행해도 같은 값을 출력받기 위해
# 0이상의 정수값은 뭐든지 ok
# 머신러닝가면 X-train, y-train, X-test, y-test로 쓰는데
# X:입력 y:출력 을 이해하기 쉬우라고 관용적 표현
# train_input, test_input, train_target, test_target으로 쓰는거

## 피처 스케일링

In [ ]:
# 피쳐스케일링

In [15]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
# 앞글자 대문자 : 클래스
# 클래스는 인스턴스 객체가 필요하니까 ss로 만들어줌
ss.fit(train_input)
# 데이터를 두개로 쪼갯지만 똑같은 특성을 둘 다 갖고잇음
# fit은 train_input 데이터 하나만 적용하면 됨
# fit은 특성을 찾는것만 하고
# 적용은 transform이 함
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)
# 이렇게하면 train_input, test_input 모두 스케일한거

In [ ]:
# 다섯개의 피쳐값들이 품종을 결정하는데 얼마나 영향이 있을까?
# 상관분석으로 관련이 있는지 확인하기

## k-최근접 이웃 분류기를 이용한 확률 예측

In [16]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 3)
# 기본값은 5갠데 3개만 줌
# 복잡하게 만드려고 이웃을 적게 함
# 모델을 복잡하게 만든다 == 과대적합을 피한다

knn.fit(train_scaled, train_target)
# 학습시키는데
# 위에서 스케일링한 데이터를 넣되 문제와 정답이 다 들어감

print(knn.score(train_scaled, train_target))
print(knn.score(test_scaled, test_target))
# 점수가 낮아도 지금은 확률을 가지고 예측하는거기때문에 신경안써도 됨

0.8907563025210085
0.85


In [17]:
# 일곱개의 생선을 다섯개의 특성으로 분류
# 다중분류

In [18]:
knn.classes_
# _ : 언더스코어라고 부름. 학습으로 새롭게 만들어진거. _가 붙으며 표시된다
# 처음에 unique로 뽑은 결과와 내용은 같은데 순서가 다름
# 타깃값은 알파벳순서로 되어있음

array(['Bream', 'Parkki', 'Perch', 'Pike', 'Roach', 'Smelt', 'Whitefish'],
      dtype=object)

In [19]:
knn.predict(test_scaled[:5])
# knn의 predict라는 함수로 예측값 보기
# 테스트데이터(스케일링한거)의 다섯개만

array(['Perch', 'Smelt', 'Pike', 'Perch', 'Perch'], dtype=object)

In [21]:
# 왜 ['Perch', 'Smelt', 'Pike', 'Perch', 'Perch']로 나왓는지 확률을 보자
# predict_proba() : 클래스별 확률값을 반환해주는 메서드
proba = knn.predict_proba(test_scaled[:5])

# 확률이라 소숫점 자리수가 길 수 있어서 반올림도 함
np.round(proba, decimals=4)
# 넘파이의 round함수는 쓰는 법이 좀 다름
# decimals : 유지할 소숫점 자릿수

# 결과값의 한 줄이 knn.classes_의 값
# ['Bream', 'Parkki', 'Perch', 'Pike', 'Roach', 'Smelt', 'Whitefish']

array([[0.    , 0.    , 1.    , 0.    , 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    , 0.    , 0.    , 1.    , 0.    ],
       [0.    , 0.    , 0.    , 1.    , 0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.6667, 0.    , 0.3333, 0.    , 0.    ],
       [0.    , 0.    , 0.6667, 0.    , 0.3333, 0.    , 0.    ]])

In [22]:
# 이렇게 계산된 확률이 진짜 맞을까?
# 다시 확인하기 위해 이웃을 분석해보자

In [23]:
# 거리와 인덱스 가져오기
distances, indexes = knn.kneighbors(test_scaled[3:4])
# test_scaled[3:4] 이렇게쓰면 인덱스가 3인 애만 가져옴

train_target[indexes]
# 저 인덱스에 해당하는것만 추출
# 이웃수를 3으로 줘서 세개가 뜸
# 값을 보니 분류가 잘된것같음
# 그런데 이웃수 3으로 예측한게 올바른 확률이라고 얘기하기 어려움
# 이웃수를 늘리면 일반화가 떨어지고..
# 그래서 우리는 로지스틱 회귀를 배운다

array([['Roach', 'Perch', 'Perch']], dtype=object)

### 로지스틱 회귀(이진 분류)

In [27]:
arr = np.array(['A', 'B', 'C', 'D', 'E'])
# 넘파이 배열에서 A와 C만 떼어내고 싶을때
# boolean indexing 불린값을 가지고 인덱싱 처리하는거
boolean = [True, False, True, False, False]
arr[boolean]

array(['A', 'C'], dtype='<U1')

In [26]:
fish.head()

Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961
3   Bream   363.0    29.0      33.5  12.7300  4.4555
4   Bream   430.0    29.0      34.0  12.4440  5.1340

In [28]:
# Bream, Smelt 이 데이터만 이용한 이진분류 학습
# Bream, Smelt만 떼오는 방법
indexes = (train_target == 'Bream') | (train_target == 'Smelt')

# 담기
train = train_scaled[indexes]
target = train_target[indexes]
# train으로 학습하고 test로 검사할건데
# 일단은 train만 쓸거니까 스케일링하고 변수에 담는거
# 지금은 fit하기 전. 이제 변수에 담아서 쓸거임

In [30]:
print(test_input.shape, test_target.shape)
# 관측데이터는 40개가 있었고

(40, 5) (40,)


In [31]:
print(train_input.shape, train_target.shape)
# 트레인 데이터는 119개가 있음

(119, 5) (119,)


In [35]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
# 지금은 파라미터 안줌

# 피팅하기
lr.fit(train, target)

LogisticRegression()

In [36]:
lr.predict(train[:5])
# predict를 이용해서 다섯개만 예측값 보기

array(['Bream', 'Smelt', 'Bream', 'Bream', 'Bream'], dtype=object)

In [38]:
lr.classes_
# 아까 클래스에 담앗던거 어떻게 담겻는지 확인
# 언버스코어(언더바)는 피팅을 통해 만들어진거(재확인)
# 첫번째가 bream
# 두번째가 smelt

array(['Bream', 'Smelt'], dtype=object)

In [37]:
# 예측확률 보기
# 트레인 데이터 5개만
lr.predict_proba(train[:5])
# 나온 결과값의 왼쪽이 음성 오른쪽이 양성 확률임
# 둘을 합치면 1

array([[0.99759855, 0.00240145],
       [0.02735183, 0.97264817],
       [0.99486072, 0.00513928],
       [0.98584202, 0.01415798],
       [0.99767269, 0.00232731]])

In [39]:
# 기울기와 절편도 골라낼수잇음
print(lr.coef_, lr.intercept_)
# 다섯개의 관측값에 대한 가중치(기울기)와 절편

[[-0.4037798  -0.57620209 -0.66280298 -1.01290277 -0.73168947]] [-2.16155132]


In [40]:
fish.head()
# 특성 순서대로 위에 나온 가중치에 곱함

Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961
3   Bream   363.0    29.0      33.5  12.7300  4.4555
4   Bream   430.0    29.0      34.0  12.4440  5.1340

In [42]:
# z값 계산
# train데이터 다섯개만
decisions = lr.decision_function(train[:5])
decisions
# z값은 -무한대 +무한대로 가기때문에 이대로 못쓰고
# 로지스틱함수/시그모이드 함수를 통과시켜서 0~1사이 확률값으로 바꿔서 쓴다

array([-6.02927744,  3.57123907, -5.26568906, -4.24321775, -6.0607117 ])

In [44]:
# 시그모이드 함수를 통해 확률값 추출
# 공식은 얘가 갖고있다 굿
from scipy.special import expit
expit(decisions)
# 나온 확률값은 lr.predict_proba(train[:5])의 양성값(오른쪽)값과 똑같다
# 음성값은 1에서 양성값을 뺀것과 같다

array([0.00240145, 0.97264817, 0.00513928, 0.01415798, 0.00232731])

## 로지스틱 회귀(다중 분류)

In [47]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(C=20, max_iter=1000) 
# C의 기본값은 1인데 좀 복잡한 모델을 만들기위해서 20을 줘서 규제줄임
# C는 알파와 반대로 작을수록 규제가 커짐
# max_lter 데이터가 많이때문에 각각의 데이터에 대한 클래스를 만들어줌
# 기본값은 100인데 부족할까봐 1000해줌
# 데이터가 많아졌기 때문에 ()안에 파라미터값을 조정해야됨lr.fit(train_scaled, train_target)
print(lr.score(train_scaled, train_target))
print(lr.score(test_scaled, test_target))

0.9327731092436975
0.925


In [48]:
lr.predict(test_scaled[:5])

array(['Perch', 'Smelt', 'Pike', 'Roach', 'Perch'], dtype=object)

In [49]:
proba = lr.predict_proba(test_scaled[:5])
np.round(proba, decimals=3)
# 소숫점이하 셋째자리까지 표시(넷째자리에서반올림)
# 생선이 일곱종류가 일곱개 나옴

# 얘는 소프트맥스가 끝임..
# 엥?

array([[0.   , 0.014, 0.841, 0.   , 0.136, 0.007, 0.003],
       [0.   , 0.003, 0.044, 0.   , 0.007, 0.946, 0.   ],
       [0.   , 0.   , 0.034, 0.935, 0.015, 0.016, 0.   ],
       [0.011, 0.034, 0.306, 0.007, 0.567, 0.   , 0.076],
       [0.   , 0.   , 0.904, 0.002, 0.089, 0.002, 0.001]])

In [50]:
lr.classes_
# 모델을 학습시켜서 생겨나는 변수라 _가 붙어잇음
# 위에랑 맞춰보면 잘 맞음

array(['Bream', 'Parkki', 'Perch', 'Pike', 'Roach', 'Smelt', 'Whitefish'],
      dtype=object)